# Enterprise CI/CD Pipeline - Production deployment với Doppler + Cloudflare Pages
name: CD Pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  PNPM_VERSION: "10.15.1"
  NODE_VERSION: "20"

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build Production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Doppler CLI
        uses: dopplerhq/cli-action@v3

      - name: Build with Doppler
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
        run: |
          echo "Building with Doppler environment injection..."
          doppler run --token="$DOPPLER_TOKEN" --project="exe-courses-fe" --config="prd_frontend" -- pnpm nx build fe-react-web --prod

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist/apps/fe-react-web
          retention-days: 1

  deploy:
    name: Deploy to Cloudflare Pages
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: dist/apps/fe-react-web

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist/apps/fe-react-web --project-name=exe-groups --compatibility-date=2023-05-18

      - name: Health check
        run: |
          echo "Deployment completed successfully!"
          echo "Site URL: https://exe-groups.pages.dev"
